---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: tier1
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: tier1
      displayName: tier1
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: tier1-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: tier1
    spec:
      namespaceSelector:
        names:
          - "azure-eastus/tier1"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: tier1-gg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: tier1
        tsb.tetrate.io/workspace: tier1-ws
    spec:
      namespaceSelector:
        names:
          - "azure-centralus/tier1"
      configMode: BRIDGED
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: tier1-tg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: tier1
        tsb.tetrate.io/workspace: tier1-ws
    spec:
      namespaceSelector:
        names:
          - "azure-centralus/tier1"
      configMode: BRIDGED
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: tier1-sg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: tier1
        tsb.tetrate.io/workspace: tier1-ws
    spec:
      namespaceSelector:
        names:
          - "azure-centralus/tier1"
      configMode: BRIDGED
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Gateway
    metadata:
      name: tier1-gw
      namespace: tier1
    spec:
      #eastWestOnly: true
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: tier1-gateway
      namespace: tier1
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: tier1
        tsb.tetrate.io/workspace: tier1-ws
        tsb.tetrate.io/gatewayGroup: tier1-gg
    spec:
      workloadSelector:
        namespace: tier1
        labels:
          app: tier1-gw
      http:
      - name: bookinfo-http
        port: 80
        hostname: bookinfo.tetrate.io
        routing:
          rules:
            - redirect:
                authority: bookinfo.tetrate.io
                port: 443
                redirectCode: 301
                scheme: https
      - name: bookinfo-https
        hostname: bookinfo.tetrate.io
        port: 443
        tls:
          mode: SIMPLE
          secretName: bookinfo-cert
        routing:
          rules:
            - match:
                - uri:
                    prefix: "/productpage"
              route:
                clusterDestination:
                  clusters:
                    - name: azure-centralus
                      weight: 50
                    - name: azure-eastus
                      weight: 50