version: '3'

tasks:
  deploy:app:
    desc: Deploy Bookinfo app and Gateway to all clusters
    cmds:
      - ./scripts/deploy-app.sh
  
  deploy:edge:
    desc: Deploy Edge configuration
    cmds:
      - ./scripts/deploy-edge.sh
  
  deploy:app-gw-failover:
    desc: Perform App GW failover 
    cmds:
      - ./scripts/app-gw-failover.sh

  deploy:east-west:
    desc: Deploy East West Gateway and configure it
    cmds:
      - ./scripts/east-west.sh

  deploy:ew-failover:
    desc: Perform East West Gateway failover
    cmds:
      - ./scripts/ew-failover.sh