---
apiVersion: v1
kind: List
items:
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: bookinfo-gw
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: bookinfo-sidecar
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      workloadSelector:
        namespace: bookinfo
        labels:
          app: bookinfo-gw
      http:
        - name: bookinfo-ssl
          port: 443
          hostname: "bookinfo.tetrate.io"
          tls:
            mode: SIMPLE
            secretName: bookinfo-cert
          routing:
            rules:
              - route:
                  serviceDestination:
                    host: "bookinfo/productpage.bookinfo.svc.cluster.local"