---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: bookinfo
      annotations:
        tsb.tetrate.io/organization: tetrate
    spec:
      description: bookinfo Application Tenant
      displayName: bookinfo 
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: bookinfo-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: bookinfo
      labels:
        app: bookinfo
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-gg-centralus
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: bookinfo
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "azure-centralus/bookinfo"
      configMode: BRIDGED
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-gg-eastus
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: bookinfo
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "azure-eastus/bookinfo"
      configMode: BRIDGED
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-tg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: bookinfo
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
      configMode: BRIDGED
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-sg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: bookinfo
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
      configMode: BRIDGED


